---
title: "Lab 09"
author: "Yumeng Gao"
date: "`r Sys.Date()`"
output: 
    html_document: default
    word_document: default
    github_document:
    pdf_document: default
    html_preview: false
always_allow_html: true
---

(Rscript --vanilla -e 'rmarkdown::render("README.Rmd", output_format= "all")')

## Problem 2.

1. Create a n x k matrix of Poisson variables with mean lambda
```{r}
set.seed(1235)
fun1 <- function(n = 100, k = 4, lambda = 4) {
  x <- NULL
  
  for (i in 1:n)
    x <- rbind(x, rpois(k, lambda))
  
  return(x)
}

f1=fun1(100,4)
mean(f1)
f1=fun1(1000,4)
#f1=fun1(10000,4)
#f1=fun1(50000,4) #longer time


fun1alt <- function(n = 100, k = 4, lambda = 4) {
  x= matrix( rpois(n*k, lambda) , ncol=4)  
  return(x)
}

# Benchmarking
microbenchmark::microbenchmark(
  fun1(),
  fun1alt()
)

```


```{r}
d= matrix(1:16, ncol=4)
d
```

```{r}
diag(d)
d[2]
d[2,1]
d[c(1,6,11,16)]
```


## Problem 3.

Find the column max (hint: Checkout the function max.col()).
```{r}
# Data Generating Process (10 x 10,000 matrix)
set.seed(1234)
M <- matrix(runif(12,), ncol=4)
M

# Find each column's max value
fun2 <- function(x) {
  apply(x, 2, max)
  x
}
fun2(M)

fun2alt <- function(x) {
  idx= max.col(t(x))
  x[cbind(idx, 1:4)]
}
fun2alt(M)

x <- matrix(rnorm(1e4), nrow=10)

# Benchmarking
microbenchmark::microbenchmark(
  fun2(x),
  fun2alt(x)
)

```


































